version: "3.8"

services:
  valkyrie-client:
    container_name: valkyrie-client
    build:
      context: .
      dockerfile: Dockerfile
    # to use image from docker hub
    # replace the local image with the image from docker hub
    # image: haoranzhangie/valkyrie-client:main
    image: valkyrie-client:local
    ports:
      - 80:80
